<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Hands-on Lab: Accessing Your Database with RSQLite</h1>

### Welcome!

In this hands-on lab, you will learn how to connect and discover metadata from database servers with R using RSQLite.

<div class="alert alert-block alert-info" style="margin-top: 20px">
<h3>Tasks</h3>
<ol><ol><ol>
<li><a href="https://#ref6a">Prerequisites</a></li>
<li><a href="https://#ref6b">Create an R notebook</a></li>
<li><a href="https://#ref6c">Load RSQLIte</a></li>
<li><a href="https://#ref6e">Create a database connection</a></li>
<li><a href="https://#ref6f">Connection attributes</a></li>
<li><a href="https://#ref6g">Connection metadata</a></li>
<li><a href="https://#ref6h">Supported data types</a></li>
<li><a href="https://#ref6i">List of tables</a></li>
<li><a href="https://#ref6j">Columns in a table</a></li>
<li><a href="https://#ref6k">Disconnect</a></li>
<li><a href="https://#ref6l">Practice exercises</a></li>
</ol></ol></ol>
<br>
Estimated Time Needed: <strong>15 min</strong>
</div>

<a id="ref6a"></a>

<h3>a. Prerequisites</h3>

In this lab, you will use Jupyter Notebooks within Skills Network (SN) Labs to access data in an SQLite database  using RSQLite.

<a id="ref6b"></a>

<h3>b. Create an R notebook</h3>

Make sure that the notebook kernel has been set to use R (using the dropdown in the top right corner).

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0103EN-SkillsNetwork/labs/Lab%20-%20Accessing%20Your%20Database%20with%20RODBC/kernel.png">

<a id="ref6c"></a>

<h3>c. Load RSQLite</h3>

The RSQlite  package needs to be installed in your notebook. Let’s load the RSQLite package by clicking on the following cell and executing it (Shift+Enter):

In [1]:
install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", repos = NULL, type = "source", dependencies = TRUE)

Warning message in install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", :
“installation of package ‘/tmp/RtmpnfA5kt/downloaded_packages/RSQLite_0.10.0.tar.gz’ had non-zero exit status”

#### Restart Kernel

After installing the RSQLite package, it is necessary to restart R Kernel. Click **Kernel** > **Restart Kernel** from the main menu. This will register the newly installed packages. Now proceed to load the RSQLite package.

In [2]:
library("RSQLite")

<a id="ref6e"></a>

<h3>b. Create a database connection</h3>

You will use the **dbConnect() method to connect to a database in SQLite Database server**. You need to load the RSQLite driver to the connect method and pass the name of the Database in the dbconnect() method. You can give any database name. If the database does not exist, a database would be created in the SQLite database server with that name.

In [3]:
con <- dbConnect(RSQLite::SQLite(),"TestDB.sqlite")
con

<SQLiteConnection>
  Path: TestDB.sqlite
  Extensions: TRUE

<a id="ref6f"></a>

<h3>c. Connection attributes</h3>

Let’s examine the connection attributes using the attributes() method and passing the connection object as argument:

In [4]:
attributes(con)

$ptr
<pointer: 0x5deff4ea1960>

$dbname
[1] "TestDB.sqlite"

$loadable.extensions
[1] TRUE

$flags
[1] 70

$vfs
[1] ""

$ref
<environment: 0x5deff49ad5f0>

$bigint
[1] "integer64"

$extended_types
[1] FALSE

$class
[1] "SQLiteConnection"
attr(,"package")
[1] "RSQLite"

<a id="ref6g"></a>

<h3>d. Connection metadata</h3>

Now let's review the connection metadata using the `dbGetInfo()` function:

In [5]:
con.info <- dbGetInfo(con)

You can print the database version and name using the `db.version` and `dbname` attributes of the connection metadata.

In [6]:
print(con.info["db.version"])
print(con.info["dbname"])

$db.version
[1] "3.47.1"

$dbname
[1] "TestDB.sqlite"

<a id="ref6h"></a>

<h3>e. Supported data types</h3>

Let’s now examine the data types supported by the database. You will use the **dbDataType() function to display the data types** by passing the driver information and the argument whose datatype needs to be determined.

In [7]:
dbDataType(RSQLite::SQLite(), 1)
dbDataType(RSQLite::SQLite(), 1L)
dbDataType(RSQLite::SQLite(), "1")
dbDataType(RSQLite::SQLite(), TRUE)
dbDataType(RSQLite::SQLite(), list(raw(1)))

sapply(datasets::quakes, dbDataType, dbObj = RSQLite::SQLite())

[1] "REAL"

[1] "INTEGER"

[1] "TEXT"

[1] "INTEGER"

[1] "BLOB"

      lat      long     depth       mag  stations
   "REAL"    "REAL" "INTEGER"    "REAL" "INTEGER"

<a id="ref6i"></a>

<h3>f. List of tables</h3>

You will use the dbListTables() function to return a list of tabless (i.e. TABLEs, VIEWs, ALIASes, etc.). Initially there will be no tables in the sqlite db which you have created. So, you will use the dbWriteTable() function to create a table in the database by passing the connection object, name of the table and an R dataset name. Here, you will create a **table called 'mtcars' in the dataset mtcars.**

In [8]:
dbListTables(con)
dbWriteTable(con, "mtcars", mtcars)

character(0)

In [11]:
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

You will again use the dbListTables() after creating a table in the database:

In [9]:
dbListTables(con)

[1] "mtcars"

<a id="ref6j"></a>

<h3>g. Columns in a table</h3>

Next, let’s look at column metadata for columns in the table **mtcars**:

In [10]:
tables1 = dbListTables(con)
for (table in tables1){  
        cat ("\nColumn info for table", table, ":\n")
        col.detail <- dbColumnInfo(dbSendQuery(con,paste( "select * from",table)))
        print(col.detail)
}

Column info for table mtcars :
   name   type
1   mpg double
2   cyl double
3  disp double
4    hp double
5  drat double
6    wt double
7  qsec double
8    vs double
9    am double
10 gear double
11 carb double

<a id="ref6k"></a>

<h3>h. Disconnect</h3>

Finally, as a best practice you should close the database connection once you're done with it.

In [12]:
dbDisconnect(con)

Warning message in connection_release(conn@ptr):
“There are 1 result in use. The connection will be released when they are closed”

<a id="ref6l"></a>

### Practice exercises

##### Task 1: Connect to an SQLite database named **MyDB**

In [13]:
# Write your code here
con <- dbConnect(RSQLite::SQLite(),"MyDB")
con

<SQLiteConnection>
  Path: MyDB
  Extensions: TRUE

<details>
<summary>Click here to view/hide hint</summary>
<p>
    
```
Fill in the ...

con <- dbConnect(RSQLite::...,"<Write the name of the SQLite database>")
con
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
con <- dbConnect(RSQLite::SQLite(),"MyDB.sqlite")
con
```

</details>

##### Task 2: Display the attributes of the connection object

In [14]:
# Write your code here
attributes(con)

$ptr
<pointer: 0x5deff2c23c70>

$dbname
[1] "MyDB"

$loadable.extensions
[1] TRUE

$flags
[1] 70

$vfs
[1] ""

$ref
<environment: 0x5deff21c8d60>

$bigint
[1] "integer64"

$extended_types
[1] FALSE

$class
[1] "SQLiteConnection"
attr(,"package")
[1] "RSQLite"

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
attributes(...)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
attributes(con)
```

</details>

##### Task 3: Review the connection metadata using the dbGetInfo() function

In [15]:
# Write your code here
con.info <- dbGetInfo(con) 
print(con.info["db.version"])
print(con.info["dbname"] )

$db.version
[1] "3.47.1"

$dbname
[1] "MyDB"

<details>
<summary>Click here to view/hide hint</summary>

```
Fill in the ...
con.info <- dbGetInfo(...)
print(con.info["<Write the attribute to display database version>"])
print(con.info["<Write the attribute to display database name>"])

```
</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
con.info <- dbGetInfo(con) 
print(con.info["db.version"])
print(con.info["dbname"] )
```

</details>

##### Task 4: Examine the data types supported by the database by checking the data types of the following literals:
##### "yes", 350, FALSE, list(1,2,3)

In [16]:
# Write your code here

dbDataType(RSQLite::SQLite(), "yes")
dbDataType(RSQLite::SQLite(), 350)
dbDataType(RSQLite::SQLite(), FALSE)
dbDataType(RSQLite::SQLite(), list(1,2,3))

sapply(datasets::quakes, dbDataType, dbObj = RSQLite::SQLite())

[1] "TEXT"

[1] "REAL"

[1] "INTEGER"

[1] "BLOB"

      lat      long     depth       mag  stations
   "REAL"    "REAL" "INTEGER"    "REAL" "INTEGER"

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbDataType(RSQLite::..., <Write the argument whose datatype has to be determined>)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
dbDataType(RSQLite::SQLite(), "yes")
dbDataType(RSQLite::SQLite(), 350)
dbDataType(RSQLite::SQLite(), FALSE)
dbDataType(RSQLite::SQLite(), list(1,2,3))

sapply(datasets::quakes, dbDataType, dbObj = RSQLite::SQLite())
```
</details>

##### Task 5: Create a table named **MyData** in the data set 'iris'

In [18]:
dbListTables(con)
head(iris)

character(0)

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa
6 5.4          3.9         1.7          0.4         setosa

In [19]:
# Write your code here
dbListTables(con)
dbWriteTable(con, "MyData", iris)

character(0)

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbWriteTable(con, "<Write the name of the table to be created>", iris)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```

dbWriteTable(con, "MyData", iris)

```

</details>

##### Task 6: List the tables in the dataset 'iris'

In [20]:
# Write your code here
dbListTables(con)

[1] "MyData"

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbListTables(...)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
dbListTables(con)
```

</details>

##### Task 7: Display the column metadata for columns in the table **MyData**

In [21]:
# Write your code here
tables1 = dbListTables(con)
for (table in tables1){  
        cat ("\nColumn info for table", table, ":\n")
        col.detail <- dbColumnInfo(dbSendQuery(con,paste( "select * from",table)))
        print(col.detail)
}

Column info for table MyData :
          name      type
1 Sepal.Length    double
2  Sepal.Width    double
3 Petal.Length    double
4  Petal.Width    double
5      Species character

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
# Fill in the ...
tables1 = dbListTables(<Write your code here>)
for (table in tables1){  
        cat ("\nColumn info for table", <Write your code here>, ":\n")
        col.detail <- dbColumnInfo(dbSendQuery(<Write your code here>)))
        print(col.detail)

```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
tables1 = dbListTables(con)
for (table in tables1){  
        cat ("\nColumn info for table", table, ":\n")
        col.detail <- dbColumnInfo(dbSendQuery(con,paste( "select * from",table)))
        print(col.detail)
}
```

</details>

##### Task 8: Disconnect from the database

In [22]:
# Write your code here
dbDisconnect(con)

Warning message in connection_release(conn@ptr):
“There are 1 result in use. The connection will be released when they are closed”

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbDisconnect(...)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
dbDisconnect(con)
```

</details>

<a id="ref6o"></a>

<h3>Summary</h3>

In this lab you accessed data in a SQLite database using RSQLite connection from a R notebook in Jupyter, and discovered different metadata.

<hr>

#### Thank you for completing this lab on getting connected and querying databases using RSQLite.

<hr>

## Authors

*   [Lakshmi Holla](https://www.linkedin.com/in/lakshmi-holla-b39062149/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0103ENSkillsNetwork23619267-2022-01-01)
* [Shreya Khurana](https://www.linkedin.com/in/shreya-khurana-437211237/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0103ENSkillsNetwork896-2023-01-01)

<!--
## Changelog

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description                    |
| ----------------- | ------- | ------------- | ------------------------------------- |
| 2023-08-08   | 1.1     | Shreya Khurana        | Created revised version of the lab|
| 2022-03-08        | 1.0     | Lakshmi Holla | Created Initial Version using RSQLite |
-->
</hr>

<h2 align=center><font size = 5>Copyright &copy; IBM Corporation. All rights reserved.</h2>